# Generated by Django 4.2.6 on 2023-11-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='note',
            fields=[
                ('noteId', models.BigAutoField(primary_key=True, serialize=False)),
                ('noteTitle', models.CharField(max_length=100)),
                ('noteText', models.TextField()),
            ],
        ),
    ]
