# Generated by Django 4.2.6 on 2023-12-25 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='note',
            fields=[
                ('noteId', models.BigAutoField(primary_key=True, serialize=False)),
                ('noteTitle', models.CharField(max_length=100)),
                ('noteText', models.TextField()),
                ('noteCreationDate', models.DateTimeField(auto_now_add=True)),
                ('noteModifiedDate', models.DateTimeField(auto_now=True)),
                ('noteAuthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
